---
version: '3.7'
services:
  pmm-managed-server:
    image: ${PMM_SERVER_IMAGE:-perconalab/pmm-server:dev-latest}
    container_name: pmm-managed-server
    hostname: pmm-managed-server
    environment:
      - PATH=/root/go/bin:$PATH
      - GO_VERSION=${GO_VERSION:-1.15.x}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
      - TRAVIS_PULL_REQUEST_SHA=${TRAVIS_PULL_REQUEST_SHA}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - REVIEWDOG_GITHUB_API_TOKEN=${REVIEWDOG_GITHUB_API_TOKEN}
      - PERCONA_TEST_DBAAS=${PERCONA_TEST_DBAAS:-0}
      - ENABLE_ALERTING=1
      - ENABLE_BACKUP_MANAGEMENT=1

    # for delve
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # see https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug#what-to-do
    ulimits:
      memlock: 67108864

    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - .:/root/go/src/github.com/percona/pmm-managed
      - ./Makefile.devcontainer:/root/go/src/github.com/percona/pmm-managed/Makefile:ro
